export const ERROR_CODES = {
  // Auth errors
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_USER_EXISTS: 'AUTH_USER_EXISTS',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',

  // Booking errors
  BOOKING_NOT_FOUND: 'BOOKING_NOT_FOUND',
  BOOKING_CONFLICT: 'BOOKING_CONFLICT',
  BOOKING_INVALID_TIME: 'BOOKING_INVALID_TIME',
  BOOKING_PAST_TIME: 'BOOKING_PAST_TIME',
  BOOKING_CAPACITY_EXCEEDED: 'BOOKING_CAPACITY_EXCEEDED',
  BOOKING_UNAUTHORIZED: 'BOOKING_UNAUTHORIZED',

  // Room errors
  ROOM_NOT_FOUND: 'ROOM_NOT_FOUND',
  ROOM_UNAVAILABLE: 'ROOM_UNAVAILABLE',

  // Availability errors
  AVAILABILITY_NO_ROOMS: 'AVAILABILITY_NO_ROOMS',
  AVAILABILITY_INVALID_PARAMS: 'AVAILABILITY_INVALID_PARAMS',

  // Network errors
  NETWORK_ERROR: 'NETWORK_ERROR',
  SERVER_ERROR: 'SERVER_ERROR',
  TIMEOUT_ERROR: 'TIMEOUT_ERROR',

  // Validation errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  REQUIRED_FIELD: 'REQUIRED_FIELD',

  // Unknown
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];
